### ISSUE TITLE
More WiFi Shenanigans

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/InspectorGadget#6]
```
GC: total: 4098240, used: 20256, free: 4077984
 No. of 1-blocks: 225, 2-blocks: 51, max blk sz: 264, max free sz: 253750
Sleeping ...

..........

.........

.I (255511) wifi:bcn_timout,ap_probe_send_start
..I (258011) wifi:ap_probe_send over, resett wifi status to disassoc
I (258011) wifi:state: run -> init (c800)
I (258011) wifi:pm stop, total sleep time: 214779612 us / 237570459 us

I (258021) wifi:new:<8,0>, old:<8,0>, ap:<255,255>, sta:<8,0>, prof:1
I (258031) wifi: STA_DISCONNECTED, reason:200
beacon timeout
..I (260081) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (262141) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (264201) wifi: STA_DISCONNECTED, reason:201
no AP found


.I (266251) wifi: STA_DISCONNECTED, reason:201
no AP found
...I (268311) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (270361) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (272421) wifi: STA_DISCONNECTED, reason:201
no AP found
.

I (274471) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (276531) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (278581) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (280641) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (282691) wifi: STA_DISCONNECTED, reason:201
no AP found
.

I (284751) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (286811) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (288861) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (290921) wifi: STA_DISCONNECTED, reason:201
no AP found
..I (292971) wifi: STA_DISCONNECTED, reason:201
no AP found
.
Starting loop 5 of 25
Checking WiFi status ...
WiFi is no bueno!
I (296361) network: event 1
Found the following access points:
Traceback (most recent call last):
  File "boot.py", line 77, in <module>
  File "main.py", line 42, in go
  File "utils_wifi.py", line 157, in checkWifiStatus
KeyError: ssid
MicroPython v1.13 on 2020-09-02; ESP32 module (spiram) with ESP32
Type "help()" for more information.
>>> [ ttyUSB0: 2020-10-03 11:03:58 ]
I (378021) event: station ip lost
I (378021) network: event 8
[ ttyUSB0: 2020-10-03 11:05:19 ]
[ ttyUSB0: 2020-10-03 11:48:31 ]
```

**Comment by astrobokonon** [comment]
Not sure what the problem was here - I switched to a new AP, but the cynomys never connected to the new one.  Not sure why, maybe I had to explicitly disconnect from the old one since they had the same ssid?

**Comment by astrobokonon** [comment]
Wasn't accounting for the case where we just don't find any good access points after the scan.  The above should fix that but it's just being tested now.

**Comment by astrobokonon** [comment]
Ok, closing again.  Be back hopefully never.
