### ISSUE TITLE
Rare wifi crash

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/InspectorGadget#8]
This was a weird one; found the board in a catatonic and uncaught error state, so I reset it and got this upon reset

```
>>> machine.reset()
I (1529071) wifi:flush txq
I (1529071) wifi:stop sw txq
I (1529071) wifi:lmac stop hw txq
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5008
ho 0 tail 12 room 4
load:0x40078000,len:11608
ho 0 tail 12 room 4
load:0x40080400,len:6120
entry 0x400806bc
I (609) psram: This chip is ESP32-D0WD
I (609) spiram: Found 64MBit SPI RAM device
I (610) spiram: SPI RAM mode: flash 40m sram 40m
I (612) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (620) cpu_start: Pro cpu up.
I (623) cpu_start: Application information:
I (628) cpu_start: Compile time:     Sep  2 2020 03:01:29
I (634) cpu_start: ELF file SHA256:  0000000000000000...
I (640) cpu_start: ESP-IDF:          v3.3.2
I (645) cpu_start: Starting app cpu, entry point is 0x40083574
I (635) cpu_start: App cpu up.
I (1521) spiram: SPI SRAM memory test OK
I (1521) heap_init: Initializing. RAM available for dynamic allocation:
I (1522) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (1528) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (1534) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (1540) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (1546) heap_init: At 3FFCABA8 len 00015458 (85 KiB): DRAM
I (1552) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1559) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1565) heap_init: At 4009A528 len 00005AD8 (22 KiB): IRAM
I (1572) cpu_start: Pro cpu start user code
I (248) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (540) modsocket: Initializing
WiFi is no bueno!
I (6410) wifi:wifi driver task: 3ffd1308, prio:23, stack:3584, core=0
I (13071) system_api: Base MAC address is not set, read default base MAC address
 from BLK0 of EFUSE
I (13071) system_api: Base MAC address is not set, read default base MAC address
 from BLK0 of EFUSE
I (13111) wifi:wifi firmware version: 44aa95c
I (13111) wifi:config NVS flash: enabled
I (13111) wifi:config nano formating: disabled
I (13111) wifi:Init dynamic tx buffer num: 32
I (13121) wifi:Init data frame dynamic rx buffer num: 32
I (13121) wifi:Init management frame dynamic rx buffer num: 32
I (13131) wifi:Init management short buffer num: 32
I (13131) wifi:Init static rx buffer size: 1600
I (13141) wifi:Init static rx buffer num: 10
I (13141) wifi:Init dynamic rx buffer num: 32
I (13241) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
I (13241) wifi:mode : sta (30:ae:a4:cc:23:cc)
I (13251) wifi: STA_START
I (15301) network: event 1
Traceback (most recent call last):
  File "boot.py", line 74, in <module>
  File "boot.py", line 43, in init
  File "utils_wifi.py", line 151, in checkWifiStatus
  File "utils_wifi.py", line 12, in scanWiFi
RuntimeError: Wifi Unknown Error 0x0102
MicroPython v1.13 on 2020-09-02; ESP32 module (spiram) with ESP32
Type "help()" for more information.
```

resetting the board one more time brought it back, but it makes sense since I'm not setting the WDT until after the wifi connects.  Maybe there's a way to clean this up even more?

**Comment by astrobokonon** [comment]
Been thinking about this one more, and I think I ran into two different bugs.

- network drops that happen in the middle of a http request hang the board.  The WDT should have caught that though
- a quick reboot might not be enough to snap the wifi out of it if things are particularly messy on the ESP side of the board

Can't do too much about the second one without debugging the board, and it's honestly not worth it.  Going to take a look at the first one though, and I might reorganize the WDT setup to make it start earlier and hopefully catch this.

**Comment by astrobokonon** [comment]
LOL the WDT didn't catch this crash because I never put the WDT in place for the Mezzanine sensor!  I only put it on the cynomys in the Dyer dome which is the ds18x20 variant.  I guess I should have unified the two more but since the BME has humidity and pressure I was lazy and thought they were different enough.  Whoops!

![2323](https://user-images.githubusercontent.com/1168555/106305655-2e46dd80-621a-11eb-9b7f-91dc45f2cb44.jpg)

**Comment by astrobokonon** [comment]
Should be fixed by 99961c5d5f773de22f454a19991caf0a066bc9a9 and f3fb644ea076c3923b5c64f406fe5d99a2e66cc0; testing now.  Had to change things over to use ```config.json``` too, which changed the DB config slightly, so data are orphaned in an old tag for now and I'll have to move that over by hand.

**Comment by astrobokonon** [comment]
Seems ok.  Going to try to get the DB reorg done today, and then I'll close this when at least this portion of that migration is done.

**Comment by astrobokonon** [comment]
Turns out I can't really easily migrate data between tags, but I at least remembered to change the retention period; leaving the old queries in the plots as a reminder.
